In [1]:
# Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(arr)

# Interchange rows and columns using transpose
arr_transposed = arr.T

print("\nArray with rows and columns interchanged:")
print(arr_transposed)


Original array:
[[18 31 36]
 [70 19 41]
 [54 81 20]]

Array with rows and columns interchanged:
[[18 70 54]
 [31 19 81]
 [36 41 20]]


In [2]:
 # Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.import numpy as np

# Generate a 1D NumPy array with 10 elements
arr = np.arange(1, 11)  # This creates an array [1, 2, 3, ..., 10]

print("Original 1D array:")
print(arr)

# Reshape into a 2x5 array
arr_2x5 = arr.reshape(2, 5)

print("\nReshaped into a 2x5 array:")
print(arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr_2x5.reshape(5, 2)

print("\nReshaped into a 5x2 array:")
print(arr_5x2)


Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped into a 2x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into a 5x2 array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [3]:
# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
import numpy as np

# Create a 4x4 NumPy array with random float values
arr = np.random.rand(4, 4)

print("Original 4x4 array:")
print(arr)

# Create a new 6x6 array filled with zeros
arr_6x6 = np.zeros((6, 6))

# Place the original 4x4 array in the center of the 6x6 array
arr_6x6[1:5, 1:5] = arr

print("\nResulting 6x6 array with border of zeros:")
print(arr_6x6)


Original 4x4 array:
[[0.8957532  0.41122738 0.23657406 0.8034657 ]
 [0.48640707 0.09450008 0.6904271  0.98785549]
 [0.68117448 0.05827913 0.56510258 0.28125197]
 [0.44420159 0.73754394 0.66852263 0.50976543]]

Resulting 6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.8957532  0.41122738 0.23657406 0.8034657  0.        ]
 [0.         0.48640707 0.09450008 0.6904271  0.98785549 0.        ]
 [0.         0.68117448 0.05827913 0.56510258 0.28125197 0.        ]
 [0.         0.44420159 0.73754394 0.66852263 0.50976543 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
# Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with step 5:")
print(arr)


Array of integers from 10 to 60 with step 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [6]:
# Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
arr_str = np.array(['python', 'numpy', 'pandas'])

# Convert elements to uppercase
arr_upper = np.char.upper(arr_str)

# Convert elements to lowercase
arr_lower = np.char.lower(arr_str)

# Convert elements to title case
arr_title = np.char.title(arr_str)

# Convert elements to capitalize case
arr_capitalize = np.char.capitalize(arr_str)

# Print the original and transformed arrays
print("Original array:")
print(arr_str)

print("\nUppercase:")
print(arr_upper)

print("\nLowercase:")
print(arr_lower)

print("\nTitle case:")
print(arr_title)

print("\nCapitalize case:")
print(arr_capitalize)


Original array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title case:
['Python' 'Numpy' 'Pandas']

Capitalize case:
['Python' 'Numpy' 'Pandas']


In [11]:
# Q6 Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create a NumPy array of words
arr_words = np.array(['python', 'numpy', 'pandas'])

# Define a function to insert space between characters of a word
insert_space = np.frompyfunc(lambda x: ' '.join(list(x)), 1, 1)

# Apply the function to each word in the array
arr_spaced = insert_space(arr_words)

# Print the original and spaced arrays
print("Original array:")
print(arr_words)

print("\nArray with spaces between characters:")
print(arr_spaced)


Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [16]:
# Q7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays of integers
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[2, 3, 4],
                 [1, 2, 3]])

# Element-wise addition
addition = arr1 + arr2

# Element-wise subtraction
subtraction = arr1 - arr2

# Element-wise multiplication
multiplication = arr1 * arr2

# Element-wise division with conversion to float
division = arr1.astype(float) / arr2

# Print the results
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nElement-wise addition:")
print(addition)

print("\nElement-wise subtraction:")
print(subtraction)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nElement-wise division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[2 3 4]
 [1 2 3]]

Element-wise addition:
[[3 5 7]
 [5 7 9]]

Element-wise subtraction:
[[-1 -1 -1]
 [ 3  3  3]]

Element-wise multiplication:
[[ 2  6 12]
 [ 4 10 18]]

Element-wise division:
[[0.5        0.66666667 0.75      ]
 [4.         2.5        2.        ]]


In [17]:
# Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix using numpy
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract diagonal elements using numpy's diagonal function
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [18]:
# Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True  # 2 is prime
    if num % 2 == 0:
        return False  # Even number other than 2
    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
np.random.seed(0)  # For reproducibility
arr = np.random.randint(0, 1001, 100)

# Find and display all prime numbers in the array
primes = [num for num in arr if is_prime(num)]

print("Generated array:")
print(arr)

print("\nPrime numbers in the array:")
print(primes)


Generated array:
[684 559 629 192 835 763 707 359   9 723 277 754 804 599  70 472 600 396
 314 705 486 551  87 174 600 849 677 537 845  72 777 916 115 976 755 709
 847 431 448 850  99 984 177 755 797 659 147 910 423 288 961 265 697 639
 544 543 714 244 151 675 510 459 882 183  28 802 128 128 932  53 901 550
 488 756 273 335 388 617  42 442 543 888 257 321 999 937  57 291 870 119
 779 430  82  91 896 398 611 565 908 633]

Prime numbers in the array:
[359, 277, 599, 677, 709, 431, 797, 659, 151, 53, 617, 257, 937]


In [20]:
# Q10. 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.
import numpy as np

# Generate random daily temperatures for a month (28-31 days)
num_days = np.random.randint(28, 32)  # Generate a random number of days between 28 and 31
temperatures = np.random.randint(15, 35, num_days)  # Generate random temperatures between 15 and 35 degrees

# Display the generated daily temperatures
print("Daily temperatures (in degrees Celsius):")
print(temperatures)

# Calculate weekly averages
# Determine the number of full weeks and reshape accordingly
num_weeks = len(temperatures) // 7
weeks = temperatures[:num_weeks * 7].reshape(num_weeks, 7)

# Calculate the mean (average) of each row (weekly averages)
weekly_averages = np.mean(weeks, axis=1)

# Display the weekly averages
print("\nWeekly averages (in degrees Celsius):")
print(weekly_averages)



Daily temperatures (in degrees Celsius):
[31 22 24 15 25 33 26 17 17 18 18 33 29 18 32 33 29 24 16 19 25 26 23 26
 17 34 31 15 15]

Weekly averages (in degrees Celsius):
[25.14285714 21.42857143 25.42857143 24.57142857]
